import "./globals.css";
import classNames from "classnames";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-black font-[courier] text-primary">{children}</body>
    </html>
  );
}
